<?xml version="1.0" encoding="UTF-8"?>
<package format="3">
  <name>main</name>
  <version>0.0.0</version>
  <description>Mission controller (C++)</description>

  <maintainer email="ryanttran315@gmail.com">Alpaca-zip</maintainer>
  <license>AGPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>interfaces</depend>
  <depend>mavros_msgs</depend>
  <depend>rcl_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
